#!/bin/sh
# failsafe defaults: TL-WDR4900

. "${__basedir}/defaults/failsafe/tl"

firmware="${FIRMWARE_DIR}/failsafe/wdr4900v1_tp_recovery.bin"

# http://wiki.openwrt.org/toh/tp-link/tl-wdr4900#reset_button_method_no_serial_cable_needed

